package graph

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.39

import (
	"context"
	"fmt"
	"os"

	"github.com/nxtcoder19/go_graphql_api/graph/model"
	"github.com/nxtcoder19/go_graphql_api/package/mongo"
	graphql_db "github.com/nxtcoder19/go_graphql_api/src/graphql/domain"
)

// CreateLink is the resolver for the createLink field.
func (r *mutationResolver) CreateLink(ctx context.Context, input model.NewLink) (*model.Link, error) {
	db.ConnectDB(context.TODO())
	link := model.Link{
		Title:   input.Title,
		Address: input.Address,
		//User: &model.User{
		//	Name: "test",
		//},
	}

	// Call the CreateLink method with the new link
	createdLink := graphql_d.CreateLink(ctx, link.Title, link.Address)
	if createdLink == nil {
		return nil, fmt.Errorf("Failed to create link")
	}

	return createdLink, nil
	//panic(fmt.Errorf("not implemented: CreateLink - createLink"))
	//var link model.Link
	//var user model.User
	////link.Address = input.Address
	////link.Title = input.Title
	//user.Name = "test"
	//link.User = &user
	////return &link, nil
	//return graphql_d.CreateLink(ctx, input.Title, input.Address, *link.User), nil
}

// CreateUser is the resolver for the createUser field.
func (r *mutationResolver) CreateUser(ctx context.Context, input model.NewUser) (string, error) {
	panic(fmt.Errorf("not implemented: CreateUser - createUser"))
}

// Login is the resolver for the login field.
func (r *mutationResolver) Login(ctx context.Context, input model.Login) (string, error) {
	panic(fmt.Errorf("not implemented: Login - login"))
}

// RefreshToken is the resolver for the refreshToken field.
func (r *mutationResolver) RefreshToken(ctx context.Context, input model.RefreshTokenInput) (string, error) {
	panic(fmt.Errorf("not implemented: RefreshToken - refreshToken"))
}

// Links is the resolver for the links field.
func (r *queryResolver) Links(ctx context.Context) ([]*model.Link, error) {
	//panic(fmt.Errorf("not implemented: Links - links"))
	var links []*model.Link
	dummyLink := model.Link{
		Title:   "our dummy link",
		Address: "https://google.com",
		//User: &model.User{
		//	Name: "admin",
		//},
	}
	links = append(links, &dummyLink)

	return links, nil
}

// Mutation returns MutationResolver implementation.
func (r *Resolver) Mutation() MutationResolver { return &mutationResolver{r} }

// Query returns QueryResolver implementation.
func (r *Resolver) Query() QueryResolver { return &queryResolver{r} }

type mutationResolver struct{ *Resolver }
type queryResolver struct{ *Resolver }

// !!! WARNING !!!
// The code below was going to be deleted when updating resolvers. It has been copied here so you have
// one last chance to move it out of harms way if you want. There are two reasons this happens:
//   - When renaming or deleting a resolver the old code will be put in here. You can safely delete
//     it when you're done.
//   - You have helper methods in this file. Move them out to keep these resolver files clean.
var mongoUrl = os.Getenv("MONGO_URI")
var db = mongo.NewDB("xyz", mongoUrl)
var graphql_d = graphql_db.NewGraphQl(db)
